name: Automatically Create Pull Request

on:
  push:
    branches-ignore:    
      - main
      - develop
      - release

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                 
        destination_branch: "develop"                     
        pr_title: "Pulling ${{ github.ref }} into devellp"
        pr_body: ":crown: *An automated PR*"              
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   
        pr_reviewer: "wei,worker"                         
        pr_assignee: "wei,worker"                         
        pr_label: "auto-pr"                               
        pr_milestone: "Milestone 1"                       
        pr_draft: true                                    
        pr_allow_empty: true                              
        github_token: ${{ secrets.GITHUB_TOKEN }}
        