name: E-Porra Frontend

on:
  pull_request:
    branches:    
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
        env: 
          CHROME_BIN: $(which chrome)
        