name: E-Porra Frontend

on:
  pull_request:
    branches:    
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build:ci
