name: Automatically Merge

on:
  push:
    branches: [ develop ]

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'toRelease') }}
    
