name: E-Porra Frontend

on:
  push:
    branches: [ develop ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps: 
    - uses: tukasz/direct-merge-action@master 
      name: Merge Develop Into Release
      if: ${{ contains(github.event.head_commit.message, 'toRelease') }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: release
