name: Automatically Merge

on:
  push:
    branches: [ develop ]

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'toRelease') }}
    
    steps: 
    - name: Mezcla desarrollo_release
    uses: tukasz/direct-merge-action@master 
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      source-branch: desarrollo
      target-branch: release
